[plugin.video.mediathek] 0.9.3
prepare for python3: futurize

make code compatible with python3
futurize -w -2 all .py files (futurize -w -1 didn't need any changes)
add import for current script.module.future

use cls instead of self for classmethods name() and isSearchable()
fix arte import time
krypton skip listItem.setIsFolder

squashed changes from upstream master raptor2101/Mediathek:

reformat sources to adhere PEP8 formatting

fix KI.KA logo
arte fix zone title unicode exception
zdf Tree cleanup
ard prefix livestreams with "live" mirroring the webapp behaviour "live in One"
optipng for all .png
keep camelCase method, argument names
remove trailing semicolon
shorten linelengths
don't use mutable [] default argument values
replace == with  is Null
addon.xml <news>
opimize imports, drop unused imports

update addon imports to reflect current krypton repo-scripts versions

ard fix ValueError time does not match format with microseconds

use format with microseconds, fallback to old format
ValueError: time data u'2019-12-12T06:16:04.447Z'
does not match format '%Y-%m-%dT%H:%M:%SZ'
begin PEP-8 line indentation with multiples of 4